export const MOLLIE_PAYMENT_METHODS = [
  { id: 6046, paymentKey: "bancontact", name: "mollie: Bancontact" },
  { id: 6047, paymentKey: "banktransfer", name: "mollie: Bank transfer" },
  { id: 6048, paymentKey: "belfius", name: "mollie: Belfius" },
  { id: 6049, paymentKey: "creditcard", name: "mollie: Credit card" },
  { id: 6050, paymentKey: "directdebit", name: "mollie: Direct debit" },
  { id: 6051, paymentKey: "eps", name: "mollie: EPS" },
  { id: 6052, paymentKey: "giftcard", name: "mollie: Giftcard" },
  { id: 6053, paymentKey: "ideal", name: "mollie: iDEAL" },
  { id: 6054, paymentKey: "kbc", name: "mollie: KBC/CBC" },
  { id: 6055, paymentKey: "klarnapaylater", name: "mollie: Klarna Pay Later" },
  { id: 6056, paymentKey: "klarnasliceit", name: "mollie: Klarna Slice It" },
  { id: 6057, paymentKey: "klarnapaynow", name: "mollie: Klarna Pay Now" },
  { id: 6058, paymentKey: "paypal", name: "mollie: Paypal" },
  { id: 6059, paymentKey: "paysafecard", name: "mollie: Paysafecard" },
  { id: 6060, paymentKey: "przelewy24", name: "mollie: Przelewy24" },
  { id: 6061, paymentKey: "in3", name: "mollie: in3" },
  { id: 6062, paymentKey: "billie", name: "mollie: Billie" },
  { id: 6063, paymentKey: "twint", name: "mollie: Twint" },
  { id: 6064, paymentKey: "klarna", name: "mollie: Pay with Klarna" },
  { id: 6065, paymentKey: "blik", name: "mollie: BLIK" },
  { id: 6066, paymentKey: "trustly", name: "mollie: Trustly" },
  { id: 6067, paymentKey: "bancomatpay", name: "mollie: BANCOMAT Pay" },
  { id: 6068, paymentKey: "paybybank", name: "mollie: Pay by Bank" },
  { id: 6071, paymentKey: "giropay", name: "mollie: Giropay" },
  { id: 6072, paymentKey: "sofort", name: "mollie: Sofort" }
];